services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
    env_file:
      - .env

  mariadb:
    image: mariadb:10.11
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mariadb_data: